### ISSUE TITLE
Error when using with NextJS App

### ISSUE THREAD

**Issue by crivera** [elysiajs/eden#13]
Hi

I am trying to create a NextJS app using Elysia and did the following steps:

1. `bunx create-next-app`
2. `bun add elysia @elysiajs/eden`
3. Create a `server.ts` file under the src directory and add a default elysia server
4. Replace `page.tsx` with the following

```
"use client";

import { edenTreaty } from "@elysiajs/eden";
import { useEffect, useState } from "react";
import type { App } from "../server";

const app = edenTreaty<App>("http://localhost:3000");

export default function Home() {
  const [data, setData] = useState(null);
  useEffect(() => {
    app.api.test.get().then((x: any) => setData(x.data));
  }, []);
  return <div>test</div>;
}

```

When hovering over the type of the `app` I get back the return type of any.

<img width="635" alt="image" src="https://github.com/elysiajs/eden/assets/356611/a99e166f-cfc1-4411-9682-47dd0e11140e">

Is this because the file is a `tsx` file?

Thanks for any help!

**Comment by brunoeduardodev** [comment]
Hey, It's related to this discord thread: https://discord.com/channels/1044804142461362206/1149835565768900758

it's happening because bun create next-app includes "moduleResolution": "blunder" by default on .tsconfig, and this is causing some typing errors in some libraries, you can fix it by changing "blunder" to "Node" or by importing the full path to edenTreaty

import { edenTreaty } from "@elysiajs/eden/treaty"

**Comment by crivera** [comment]
That was it! Thanks a lot!
